#ifndef __ASM_REQUIRED_FEATURES_H__
#define __ASM_REQUIRED_FEATURES_H__

# define NEED_FPU	(1<<(X86_FEATURE_FPU & 31))

# define NEED_PAE	(1<<(X86_FEATURE_PAE & 31))

# define NEED_CX8	(1<<(X86_FEATURE_CX8 & 31))

# define NEED_CMOV	(1<<(X86_FEATURE_CMOV & 31))

# define NEED_3DNOW	0

# define NEED_NOPL	0

# define NEED_MOVBE	(1<<(X86_FEATURE_MOVBE & 31))

#define NEED_PSE	0
#define NEED_MSR	0
#define NEED_PGE	0
#define NEED_FXSR	0
#define NEED_XMM	0
#define NEED_XMM2	0
#define NEED_LM		0

#define REQUIRED_MASK0	(NEED_FPU|NEED_PSE|NEED_MSR|NEED_PAE|\
			 NEED_CX8|NEED_PGE|NEED_FXSR|NEED_CMOV|\
			 NEED_XMM|NEED_XMM2)

#define REQUIRED_MASK1	(NEED_LM|NEED_3DNOW)

#define REQUIRED_MASK2	0
#define REQUIRED_MASK3	(NEED_NOPL)
#define REQUIRED_MASK4	(NEED_MOVBE)
#define REQUIRED_MASK5	0
#define REQUIRED_MASK6	0
#define REQUIRED_MASK7	0
#define REQUIRED_MASK8	0
#define REQUIRED_MASK9	0

#endif /* ! __ASM_REQUIRED_FEATURES_H__ */
