#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__
/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Linux/x86 3.16.0 Kernel Configuration
 *
 */
#define CONFIG_RING_BUFFER 1

#define CONFIG_TCP_MD5SIG 1

#define CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK 1

#define CONFIG_ARCH_SUPPORTS_INT128 1

#define CONFIG_RFS_ACCEL 1

#define CONFIG_SECCOMP 1
#define CONFIG_HIGH_RES_TIMERS 1

#define CONFIG_IP_MULTIPLE_TABLES 1
#define CONFIG_UEVENT_HELPER 1

#define CONFIG_INOTIFY_USER 1

#define CONFIG_X86_TSC 1

#define CONFIG_INLINE_WRITE_UNLOCK_IRQ 1
#define CONFIG_HIBERNATION 1

#define CONFIG_FSNOTIFY 1

#define CONFIG_HAVE_MEMORY_PRESENT 1

#define CONFIG_IPV6 1

#define CONFIG_COMPAT 1
#define CONFIG_BQL 1

#define CONFIG_DEVTMPFS 1

#define CONFIG_HOTPLUG_CPU 1

#define CONFIG_WLAN 1

#define CONFIG_HAVE_CMPXCHG_DOUBLE 1

#define CONFIG_IA32_EMULATION 1

#define CONFIG_NEED_PER_CPU_PAGE_FIRST_CHUNK 1
#define CONFIG_MODULES_USE_ELF_RELA 1

#define CONFIG_USE_PERCPU_NUMA_NODE_ID 1

#define CONFIG_NET_POLL_CONTROLLER 1
#define CONFIG_PRINTK 1
#define CONFIG_NF_CONNTRACK_PROC_COMPAT 1

#define CONFIG_TIMERFD 1

#define CONFIG_TRACEPOINTS 1

#define CONFIG_SHMEM 1
#define CONFIG_MIGRATION 1

#define CONFIG_ENABLE_MUST_CHECK 1

#define CONFIG_HAVE_ARCH_SOFT_DIRTY 1

#define CONFIG_SCHEDSTATS 1

#define CONFIG_X86 1

#define CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS 1

#define CONFIG_ARCH_CLOCKSOURCE_DATA 1

#define CONFIG_AUDITSYSCALL 1

#define CONFIG_ARCH_USE_BUILTIN_BSWAP 1

#define CONFIG_ACPI 1

#define CONFIG_MTRR 1

#define CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING 1
#define CONFIG_BSD_PROCESS_ACCT 1

#define CONFIG_X86_MPPARSE 1

#define CONFIG_SCHED_MC 1

#define CONFIG_EFI 1

#define CONFIG_HAVE_SETUP_PER_CPU_AREA 1
#define CONFIG_GENERIC_EARLY_IOREMAP 1

#define CONFIG_BLOCK 1

#define CONFIG_PROVIDE_OHCI1394_DMA_INIT 1
#define CONFIG_BUG 1

#define CONFIG_PM 1

#define CONFIG_SPLIT_PTLOCK_CPUS 4

#define CONFIG_ZONE_DMA 1

#define CONFIG_X86_64_SMP 1

#define CONFIG_SPARSEMEM_EXTREME 1

#define CONFIG_TASK_XACCT 1

#define CONFIG_EVENT_TRACING 1

#define CONFIG_PREEMPT_VOLUNTARY 1

#define CONFIG_CGROUP_FREEZER 1

#define CONFIG_FS_POSIX_ACL 1
#define CONFIG_IPV6_SIT 1
#define CONFIG_XFRM 1

#define CONFIG_X86_CMOV 1

#define CONFIG_CPUSETS 1

#define CONFIG_SPARSE_IRQ 1

#define CONFIG_RCU_STALL_COMMON 1

#define CONFIG_DEBUG_BUGVERBOSE 1

#define CONFIG_X86_INTERNODE_CACHE_SHIFT 6

#define CONFIG_DEBUG_DEVRES 1

#define CONFIG_TRACE_IRQFLAGS_SUPPORT 1

#define CONFIG_TREE_RCU 1
#define CONFIG_SWIOTLB 1

#define CONFIG_HAVE_KVM 1

#define CONFIG_IP_NF_TARGET_ULOG 1
#define CONFIG_KEYS 1

#define CONFIG_TIMER_STATS 1

#define CONFIG_FUTEX 1

#define CONFIG_SECURITY_NETWORK 1

#define CONFIG_HUGETLB_PAGE 1

#define CONFIG_IPV6_NDISC_NODETYPE 1

#define CONFIG_CGROUP_SCHED 1
#define CONFIG_SYSVIPC 1

#define CONFIG_MODULES 1

#define CONFIG_NO_HZ_COMMON 1

#define CONFIG_BLK_DEV_IO_TRACE 1
#define CONFIG_XPS 1

#define CONFIG_HAVE_MEMBLOCK_NODE_MAP 1

#define CONFIG_FAIR_GROUP_SCHED 1

#define CONFIG_KPROBES 1

#define CONFIG_SLUB 1

#define CONFIG_PM_SLEEP 1

#define CONFIG_GENERIC_PENDING_IRQ 1

#define CONFIG_VM_EVENT_COUNTERS 1

#define CONFIG_GENERIC_FIND_FIRST_BIT 1

#define CONFIG_KALLSYMS 1
#define CONFIG_PCI 1

#define CONFIG_HAVE_UNSTABLE_SCHED_CLOCK 1

#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_QUEUE_RWLOCK 1

#define CONFIG_NUMA 1

#define CONFIG_EPOLL 1

#define CONFIG_NET 1

#define CONFIG_ACPI_SLEEP 1

#define CONFIG_NODES_SHIFT 6

#define CONFIG_INET 1

#define CONFIG_FREEZER 1

#define CONFIG_NET_CLS_ACT 1

#define CONFIG_X86_DEBUGCTLMSR 1

#define CONFIG_X86_LOCAL_APIC 1

#define CONFIG_NETFILTER 1
#define CONFIG_X86_DEV_DMA_OPS 1

#define CONFIG_IP_MROUTE 1
#define CONFIG_X86_SMAP 1

#define CONFIG_NF_NAT_NEEDED 1

#define CONFIG_NET_FLOW_LIMIT 1

#define CONFIG_POSIX_MQUEUE 1

#define CONFIG_ILLEGAL_POINTER_VALUE 0xdead000000000000
#define CONFIG_TASKSTATS 1

#define CONFIG_NEED_DMA_MAP_STATE 1

#define CONFIG_QUOTA_NETLINK_INTERFACE 1

#define CONFIG_SMP 1

#define CONFIG_GENERIC_BUG 1

#define CONFIG_COMPAT_OLD_SIGACTION 1

#define CONFIG_X86_MCE_THRESHOLD 1

#define CONFIG_UID16 1

#define CONFIG_ASSOCIATIVE_ARRAY 1
#define CONFIG_NF_DEFRAG_IPV6 1

#define CONFIG_INLINE_READ_UNLOCK 1
#define CONFIG_HAS_DMA 1

#define CONFIG_VT_CONSOLE_SLEEP 1

#define CONFIG_X86_64 1

#define CONFIG_DEBUG_STACK_USAGE 1
#define CONFIG_ARCH_HAS_CACHE_LINE_SIZE 1

#define CONFIG_SPARSEMEM_VMEMMAP 1

#define CONFIG_OPTIMIZE_INLINING 1

#define CONFIG_X86_THERMAL_VECTOR 1

#define CONFIG_CLOCKSOURCE_WATCHDOG 1

#define CONFIG_INLINE_READ_UNLOCK_IRQ 1

#define CONFIG_NEED_SG_DMA_LENGTH 1

#define CONFIG_PROFILING 1

#define CONFIG_SPARSEMEM 1

#define CONFIG_SCHED_SMT 1
#define CONFIG_RT_MUTEXES 1
#define CONFIG_HUGETLBFS 1

#define CONFIG_KERNFS 1

#define CONFIG_X86_IO_APIC 1
#define CONFIG_TASK_IO_ACCOUNTING 1

#define CONFIG_CGROUPS 1

#define CONFIG_CGROUP_CPUACCT 1
#define CONFIG_HAS_IOPORT_MAP 1
#define CONFIG_X86_CMPXCHG64 1

#define CONFIG_HZ 1000

#define CONFIG_NEED_MULTIPLE_NODES 1

#define CONFIG_INLINE_SPIN_UNLOCK_IRQ 1

#define CONFIG_NR_CPUS 64

#define CONFIG_SYSFS 1

#define CONFIG_TRACING 1

#define CONFIG_AMD_IOMMU 1

#define CONFIG_ARCH_ENABLE_SPLIT_PMD_PTLOCK 1

#define CONFIG_RPS 1

#define CONFIG_MUTEX_SPIN_ON_OWNER 1

#define CONFIG_HAVE_DMA_ATTRS 1

#define CONFIG_EARLY_PRINTK 1

#define CONFIG_BASE_SMALL 0

#define CONFIG_COMPACTION 1

#define CONFIG_PROC_FS 1

#define CONFIG_GENERIC_BUG_RELATIVE_POINTERS 1
#define CONFIG_IRQ_FORCED_THREADING 1

#define CONFIG_PAGEFLAGS_EXTENDED 1

#define CONFIG_SYSCTL 1
#define CONFIG_PHYS_ADDR_T_64BIT 1

#define CONFIG_TASK_DELAY_ACCT 1
#define CONFIG_NET_NS 1

#define CONFIG_GENERIC_IRQ_LEGACY_ALLOC_HWIRQ 1
#define CONFIG_HAVE_ALIGNED_STRUCT_PAGE 1
#define CONFIG_NO_BOOTMEM 1

#define CONFIG_AUDIT 1
#define CONFIG_INTEL_IOMMU 1

#define CONFIG_SECURITY 1

#define CONFIG_ACPI_NUMA 1

#define CONFIG_NET_RX_BUSY_POLL 1
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_ZONE_DMA32 1
#define CONFIG_NET_SCHED 1

#define CONFIG_SECCOMP_FILTER 1

#define CONFIG_BINARY_PRINTF 1

#define CONFIG_64BIT 1
#define CONFIG_QUOTA 1

#define CONFIG_NETWORK_SECMARK 1

#define CONFIG_ARCH_RANDOM 1

#define CONFIG_ARCH_USE_CMPXCHG_LOCKREF 1

#define CONFIG_NODES_SPAN_OTHER_NODES 1

#define CONFIG_SWAP 1

#define CONFIG_ARCH_USES_PG_UNCACHED 1

#define CONFIG_MODULE_UNLOAD 1

#define CONFIG_RWSEM_SPIN_ON_OWNER 1

#define CONFIG_X86_L1_CACHE_SHIFT 6

#define CONFIG_NF_CONNTRACK 1
#define CONFIG_ARCH_DMA_ADDR_T_64BIT 1
#define CONFIG_FILE_LOCKING 1

#define CONFIG_NETPOLL 1
#define CONFIG_AIO 1

#define CONFIG_PERF_EVENTS 1

#define CONFIG_DEBUG_RODATA 1
#define CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS 1

#define CONFIG_MMU 1

#define CONFIG_INLINE_WRITE_UNLOCK 1

#endif /* ! __AUTOCONF_H__ */
